"""Glass-Box Algorithmic Explainability & Rule Trigger Engine.

Provides transparent component attribution and active sports science rule tracing
for recommendations generated by the adaptive engine.
"""
from __future__ import annotations

from dataclasses import dataclass
from backend.engine.config import DEFAULT_CONFIG, EngineConfig
from backend.engine.scoring import clamp, session_score
from backend.engine.types import (
    AthleteState,
    CounterfactualOption,
    Decision,
    HistoryAnalysis,
    PersonalBaseline,
    Prescription,
    SessionDelta,
    SessionInput,
)


@dataclass(frozen=True)
class ComponentBreakdownData:
    perf_trend: float
    score_level: float
    rpe_signal: float
    volume_trend: float


def compute_component_breakdown(
    a: HistoryAnalysis, config: EngineConfig = DEFAULT_CONFIG
) -> ComponentBreakdownData:
    """Return the weighted contribution of each signal component to the composite signal."""
    if a.session_count == 0:
        return ComponentBreakdownData(0.0, 0.0, 0.0, 0.0)

    perf_norm = clamp(a.performance_trend / config.trend_scale, -1.0, 1.0)
    level_norm = clamp(
        (a.weighted_avg_score - config.neutral_score) / config.level_scale, -1.0, 1.0
    )
    rpe_trend_norm = clamp(-a.rpe_trend / config.rpe_trend_scale, -1.0, 1.0)
    rpe_level_norm = clamp(
        (config.rpe_target - a.weighted_avg_rpe) / config.rpe_level_scale, -1.0, 1.0
    )
    rpe_norm = 0.5 * rpe_trend_norm + 0.5 * rpe_level_norm
    volume_norm = clamp(a.volume_trend / config.volume_trend_scale, -1.0, 1.0)

    return ComponentBreakdownData(
        perf_trend=round(config.w_signal_trend * perf_norm, 2),
        score_level=round(config.w_signal_level * level_norm, 2),
        rpe_signal=round(config.w_signal_rpe * rpe_norm, 2),
        volume_trend=round(config.w_signal_volume * volume_norm, 2),
    )


def extract_triggered_rules(
    a: HistoryAnalysis,
    signal: float,
    confidence: int,
    decision: Decision,
    current: Prescription,
    nxt: Prescription,
    config: EngineConfig = DEFAULT_CONFIG,
) -> list[str]:
    """Identify which sports science rules and safety gates were activated."""
    rules: list[str] = []

    # History & Confidence Gates
    if a.session_count < config.min_sessions:
        rules.append("INSUFFICIENT_HISTORY")
    elif confidence < config.min_confidence_to_act:
        rules.append("LOW_CONFIDENCE_GATE")

    # One-Off Bad Day Guard
    # If the composite signal was otherwise positive/neutral or history was strong,
    # but the most recent session had a low score, blocking progression
    if a.session_count >= config.min_sessions:
        if a.last_score < config.poor_session_score:
            if signal >= config.progress_threshold:
                rules.append("ONE_BAD_DAY_GUARD")
            elif a.recent_poor_sessions <= 1 and decision == Decision.HOLD:
                rules.append("ONE_BAD_DAY_GUARD")

    # RPE Creep Detection
    if a.session_count >= 2:
        if (
            a.rpe_trend >= 0.15
            or a.weighted_avg_rpe > config.rpe_progress_max
            or a.weighted_avg_rpe >= config.rpe_high
        ):
            rules.append("RPE_CREEP_DETECTED")

    # Decision-specific triggers
    if decision == Decision.PROGRESS:
        rules.append("SUPERCOMPENSATION_PROGRESSION")
        if nxt.weight > current.weight and current.reps >= config.rep_ceiling:
            rules.append("DOUBLE_PROGRESSION_REP_CEILING")
        elif nxt.reps > current.reps and nxt.weight == current.weight:
            rules.append("DOUBLE_PROGRESSION_REPS_ADDED")

    elif decision == Decision.BACK_OFF:
        if a.recent_poor_sessions >= config.backoff_min_poor_sessions:
            rules.append("PERSISTENT_FATIGUE_BACKOFF")
        if nxt.sets < current.sets:
            rules.append("FATIGUE_SET_REDUCTION")

    elif decision == Decision.HOLD:
        if (
            "ONE_BAD_DAY_GUARD" not in rules
            and "LOW_CONFIDENCE_GATE" not in rules
            and "INSUFFICIENT_HISTORY" not in rules
        ):
            rules.append("PLATEAU_MAINTENANCE")

    return rules


def build_coaching_rationale(
    decision: Decision,
    a: HistoryAnalysis,
    signal: float,
    confidence: int,
    rules: list[str],
    current: Prescription,
    nxt: Prescription,
) -> str:
    """Generate high-clarity sports science explanation emphasizing the why."""
    if "ONE_BAD_DAY_GUARD" in rules:
        return (
            "You completed target volume previously, but your latest session experienced acute fatigue. "
            "Holding steady to prevent systemic breakdown from an isolated bad day."
        )

    if "RPE_CREEP_DETECTED" in rules and decision == Decision.HOLD:
        return (
            f"You completed target volume, but your perceived exertion climbed across recent sessions "
            f"(weighted RPE {a.weighted_avg_rpe:.1f}). Holding steady to prevent systemic fatigue."
        )

    if decision == Decision.PROGRESS:
        if "DOUBLE_PROGRESSION_REP_CEILING" in rules:
            return (
                f"You conquered the rep ceiling ({current.reps} reps) with consistent effort. "
                f"Advancing working load to {nxt.weight} kg while resetting to base rep floor."
            )
        if "DOUBLE_PROGRESSION_REPS_ADDED" in rules:
            return (
                f"Solid adaptation demonstrated. Adding +1 rep to your sets ({nxt.reps} reps) "
                f"to drive progressive overload without excessive plate jumps."
            )
        return (
            f"Strong positive adaptation detected (signal +{signal:.2f}, confidence {confidence}%). "
            f"Advancing target load from {current.weight} kg to {nxt.weight} kg."
        )

    if decision == Decision.BACK_OFF:
        reason = "escalating effort and missed volume" if "RPE_CREEP_DETECTED" in rules else "accumulated fatigue"
        sets_msg = f" and reduced volume to {nxt.sets} sets" if nxt.sets < current.sets else ""
        return (
            f"Multi-session decline detected ({reason} across {a.recent_poor_sessions} recent sessions). "
            f"Deloading load to {nxt.weight} kg{sets_msg} to facilitate physiological recovery."
        )

    if "LOW_CONFIDENCE_GATE" in rules:
        return (
            f"Performance signals are currently variable (confidence {confidence}%). "
            "Holding steady until movement consistency stabilizes."
        )

    if "INSUFFICIENT_HISTORY" in rules:
        return (
            f"Establishing baseline ({a.session_count} of 3 sessions logged). "
            "Maintaining prescribed load to calibrate adaptation velocity."
        )

    return (
        f"Steady plateau maintained across recent sessions (weighted score {a.weighted_avg_score:.0f}/100). "
        f"Holding current prescription ({current.weight} kg × {current.reps} × {current.sets}) for another session."
    )


def estimate_athlete_state(
    a: HistoryAnalysis,
    signal: float,
    confidence: int,
    decision: Decision,
    readiness_modifier: float = 0.0,
) -> AthleteState:
    """Estimate comprehensive athlete training state from objective + subjective signals."""
    base_readiness = 75.0 + readiness_modifier * 200.0
    if a.weighted_avg_rpe >= 8.5:
        base_readiness -= 10.0
    elif a.weighted_avg_rpe <= 6.5:
        base_readiness += 8.0
    readiness_pct = int(round(clamp(base_readiness, 20.0, 98.0)))

    if a.performance_trend > 0.5:
        perf_status = "Improving"
    elif a.performance_trend < -0.5:
        perf_status = "Declining"
    else:
        perf_status = "Stable"

    if a.weighted_avg_rpe >= 8.5 or a.recent_poor_sessions >= 2:
        fatigue = "High"
    elif a.weighted_avg_rpe >= 7.3 or a.rpe_trend > 0.1:
        fatigue = "Moderate"
    else:
        fatigue = "Low"

    if readiness_pct >= 85:
        recovery = "Prime"
    elif readiness_pct >= 70:
        recovery = "Good"
    elif readiness_pct >= 50:
        recovery = "Adequate"
    else:
        recovery = "Poor"

    if decision == Decision.PROGRESS or signal >= 0.25:
        adaptation = "Positive"
    elif decision == Decision.BACK_OFF or signal <= -0.25:
        adaptation = "Fatigue Accumulation"
    else:
        adaptation = "Neutral"

    return AthleteState(
        readiness_pct=readiness_pct,
        performance_status=perf_status,
        fatigue_level=fatigue,
        recovery_status=recovery,
        adaptation_status=adaptation,
        confidence_pct=confidence,
    )


def compute_personal_baseline(
    sessions: list[SessionInput], config: EngineConfig = DEFAULT_CONFIG
) -> PersonalBaseline:
    """Compute athlete's historical baseline for a specific movement."""
    if not sessions:
        return PersonalBaseline(
            typical_rpe=config.rpe_target,
            typical_score=config.neutral_score,
            typical_volume=0.0,
            typical_reps=8.0,
            sessions_analyzed=0,
        )
    scores = [session_score(s, config) for s in sessions]
    volumes = [s.actual_weight * s.actual_reps * s.actual_sets for s in sessions]
    rpes = [float(s.rpe) for s in sessions]
    reps = [float(s.actual_reps) for s in sessions]

    return PersonalBaseline(
        typical_rpe=round(sum(rpes) / len(rpes), 1),
        typical_score=round(sum(scores) / len(scores), 1),
        typical_volume=round(sum(volumes) / len(volumes), 1),
        typical_reps=round(sum(reps) / len(reps), 1),
        sessions_analyzed=len(sessions),
    )


def generate_counterfactuals(
    decision: Decision,
    a: HistoryAnalysis,
    signal: float,
    confidence: int,
    current: Prescription,
    nxt: Prescription,
) -> list[CounterfactualOption]:
    """Generate counterfactual statements demonstrating algorithmic explainability."""
    counterfactuals: list[CounterfactualOption] = []

    if decision == Decision.BACK_OFF:
        counterfactuals.append(
            CounterfactualOption(
                condition="If subjective recovery had been adequate (readiness >= 75%) and latest RPE <= 7.5",
                resulting_action="HOLD",
                explanation="Isolated fatigue would be held steady rather than triggering a systemic deload.",
            )
        )
        counterfactuals.append(
            CounterfactualOption(
                condition="If performance trend slope was positive (+1.5 score pts/session)",
                resulting_action="PROGRESS",
                explanation="Strong positive adaptation would outweigh perceived fatigue and permit a conservative 2.5% progression.",
            )
        )
        counterfactuals.append(
            CounterfactualOption(
                condition="If two consecutive sessions had hit RPE 10 with missed reps",
                resulting_action="DELOAD (-10% & -1 Set)",
                explanation="Deeper systemic overreaching would prompt an aggressive multi-parameter deload.",
            )
        )

    elif decision == Decision.PROGRESS:
        counterfactuals.append(
            CounterfactualOption(
                condition="If latest session RPE had escalated above 8.5",
                resulting_action="HOLD",
                explanation="Effort safety gate would trigger to prevent overloading while athlete is close to failure.",
            )
        )
        counterfactuals.append(
            CounterfactualOption(
                condition="If the latest session had missed reps (completion < 100%)",
                resulting_action="HOLD (One-Bad-Day Guard)",
                explanation="The engine would hold working load steady to prevent advancing under execution deficits.",
            )
        )
        counterfactuals.append(
            CounterfactualOption(
                condition="If confidence score was below 40% (high variance)",
                resulting_action="HOLD (Low-Confidence Gate)",
                explanation="The engine would require more consistent baseline data before stepping load.",
            )
        )

    else:  # HOLD
        counterfactuals.append(
            CounterfactualOption(
                condition="If next session is completed at target reps with RPE <= 7.0 and high recovery",
                resulting_action="PROGRESS",
                explanation="Composite signal would climb past +0.25 threshold, triggering a load progression.",
            )
        )
        counterfactuals.append(
            CounterfactualOption(
                condition="If another session exhibits missed reps or RPE >= 9.0",
                resulting_action="BACK OFF",
                explanation="Persistent multi-session fatigue would satisfy the 2-of-3 poor sessions rule for deload.",
            )
        )
        counterfactuals.append(
            CounterfactualOption(
                condition="If rep ceiling (12 reps on dumbbells) is hit across all working sets",
                resulting_action="PROGRESS (Plate Step + Rep Reset)",
                explanation="Double progression triggers load jump while resetting volume back to floor.",
            )
        )

    return counterfactuals


def compute_session_delta(
    sessions: list[SessionInput],
    current: Prescription,
    nxt: Prescription,
    config: EngineConfig = DEFAULT_CONFIG,
) -> SessionDelta:
    """Compute concise comparison against previous session."""
    load_delta = round(nxt.weight - current.weight, 2)
    reps_delta = nxt.reps - current.reps
    sets_delta = nxt.sets - current.sets

    if len(sessions) < 2:
        return SessionDelta(
            perf_delta_pct=0.0,
            rpe_delta=0.0,
            volume_delta_pct=0.0,
            load_delta=load_delta,
            reps_delta=reps_delta,
            sets_delta=sets_delta,
        )

    curr_s = sessions[-1]
    prev_s = sessions[-2]

    curr_score = session_score(curr_s, config)
    prev_score = session_score(prev_s, config)
    perf_delta_pct = round(((curr_score - prev_score) / max(prev_score, 1.0)) * 100.0, 1)

    rpe_delta = round(float(curr_s.rpe - prev_s.rpe), 1)

    curr_vol = curr_s.actual_weight * curr_s.actual_reps * curr_s.actual_sets
    prev_vol = prev_s.actual_weight * prev_s.actual_reps * prev_s.actual_sets
    volume_delta_pct = round(((curr_vol - prev_vol) / max(prev_vol, 1.0)) * 100.0, 1)

    return SessionDelta(
        perf_delta_pct=perf_delta_pct,
        rpe_delta=rpe_delta,
        volume_delta_pct=volume_delta_pct,
        load_delta=load_delta,
        reps_delta=reps_delta,
        sets_delta=sets_delta,
    )

